[package]
name = "trustedge-audio"
version = "0.1.1"
edition = "2024"

[dependencies]
aes-gcm = "0.10"         # AEAD (AES-GCM)
blake3 = "1.5"
aead = "0.5"
rand_core = "0.6"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }   # simple CLI
