# Copyright (c) 2025 John Turner
# MPL-2.0: https://mozilla.org/MPL/2.0/
# Project: trustedge — Privacy and trust at the edge.


codecov:
  require_ci_to_pass: yes
  
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
    patch:
      default:
        target: auto
        threshold: 1%
        base: auto

ignore:
  - "trustedge-audio/tests/"
  - "trustedge-audio/src/bin/"
  - "trustedge-audio/examples/"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
