# Copyright (c) 2025 TRUSTEDGE LABS LLC
# MPL-2.0: https://mozilla.org/MPL/2.0/
# Project: trustedge — Privacy and trust at the edge.


name: "CLA Assistant"

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, synchronize, closed]

jobs:
  cla:
    permissions:
      contents: write
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        # Use the official CLA Assistant Lite Action
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # The path to the CLA document.
          # Use the raw URL of the CLA document in the repository.
          path-to-document: 'https://github.com/TrustEdge-Labs/trustedge/blob/main/CLA.md'

          # The path where the signatures will be stored.
          path-to-signatures: 'signatures/cla.json'
          
          # The branch where the signatures will be committed.
          branch: 'cla-signatures'

          # A list of users to exempt from signing the CLA (e.g., bots).
          # Separate multiple users with commas.
          allowlist: bot[bot],dependabot[bot]

          # The comment to post when a contributor needs to sign.
          # Use {pullRequestAuthor} and {pathToCLADocument} as placeholders.
          comment-to-post: |
            Hi @{pullRequestAuthor}. Thank you for your contribution!
            
            To make sure we can accept your contribution, we need you to sign our Contributor License Agreement (CLA). By signing, you're confirming that you have the right to license your contribution to us and that you agree to the terms.
            
            Please read the CLA here: https://github.com/TrustEdge-Labs/trustedge/blob/main/CLA.md

            You can sign the CLA by responding to this comment with the following sentence:
            
            **I have read the CLA Document and I hereby sign the CLA**
