# Copyright (c) 2025 TRUSTEDGE LABS LLC
# MPL-2.0: https://mozilla.org/MPL/2.0/
# Project: trustedge — Privacy and trust at the edge.


name: WebAssembly Build Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'crates/wasm/**'
      - 'crates/trst-wasm/**'
      - 'crates/core/**'
      - '.github/workflows/wasm-tests.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'crates/wasm/**'
      - 'crates/trst-wasm/**'
      - 'crates/core/**'
      - '.github/workflows/wasm-tests.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  wasm-size-check:
    name: WASM Size Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true

    - name: Install wasm-pack
      run: |
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Build trustedge-wasm and check size
      run: |
        cd crates/wasm
        wasm-pack build --target web --release
        wasm_size=$(wc -c < pkg/trustedge_wasm_bg.wasm)
        echo "trustedge-wasm size: $wasm_size bytes"
        # Fail if WASM is larger than 2MB (reasonable size for crypto operations)
        if [ $wasm_size -gt 2097152 ]; then
          echo "❌ trustedge-wasm is too large: $wasm_size bytes (max: 2MB)"
          exit 1
        else
          echo "✅ trustedge-wasm size is acceptable: $wasm_size bytes"
        fi

    - name: Build trst-wasm and check size
      run: |
        cd crates/trst-wasm
        wasm-pack build --target web --release
        wasm_size=$(wc -c < pkg/trustedge_trst_wasm_bg.wasm)
        echo "trst-wasm size: $wasm_size bytes"
        # Fail if WASM is larger than 1MB (verification should be lightweight)
        if [ $wasm_size -gt 1048576 ]; then
          echo "❌ trst-wasm is too large: $wasm_size bytes (max: 1MB)"
          exit 1
        else
          echo "✅ trst-wasm size is acceptable: $wasm_size bytes"
        fi

  wasm-build-check:
    name: WASM Build Verification
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true

    - name: Install wasm-pack
      run: |
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Build and verify WASM package
      run: |
        cd crates/wasm
        # Verify WASM package builds successfully for web target
        wasm-pack build --target web --out-dir pkg-test

    - name: Verify compilation of WASM tests
      run: |
        cd crates/wasm
        # Verify WASM tests compile (without running in browser)
        cargo check --tests --target wasm32-unknown-unknown